"""
YUMBOT seed recipes v3.0 — 42 recipes across all dietary categories.
Run directly: python seed_recipes.py
"""
import json, sys, os
sys.path.insert(0, os.path.dirname(__file__))

RECIPES = [
# ── BREAKFASTS ─────────────────────────────────────────────────────────
{"name":"Creamy Blueberry Porridge","description":"A warming bowl of oats topped with fresh blueberries and a drizzle of honey.","cook_time_mins":10,"difficulty":"Easy","serves":2,"cuisine_type":"British","dietary_tags":"Vegetarian,High-Fibre,breakfast","ingredients_json":json.dumps(["100g rolled oats","400ml whole milk","100g fresh blueberries","1 tbsp honey","Pinch of salt"]),"steps_json":json.dumps(["Bring milk to a gentle simmer in a saucepan over medium heat.","Add oats and salt, stir constantly 4-5 minutes until thick and creamy.","Spoon into bowls, top with blueberries and drizzle with honey."])},

{"name":"Avocado Toast & Poached Egg","description":"Creamy avocado on toasted sourdough with a perfectly poached egg.","cook_time_mins":10,"difficulty":"Easy","serves":1,"cuisine_type":"Modern","dietary_tags":"Vegetarian,breakfast","ingredients_json":json.dumps(["2 slices sourdough bread","1 ripe avocado","2 large eggs","Juice of half a lemon","Pinch of chilli flakes","Salt and black pepper"]),"steps_json":json.dumps(["Toast bread until golden and crisp.","Mash avocado with lemon juice, salt, and pepper.","Poach eggs in simmering water for 3 minutes. Lay on toast, scatter chilli flakes."])},

{"name":"Shakshuka","description":"Eggs poached in a rich, spiced tomato and pepper sauce.","cook_time_mins":25,"difficulty":"Easy","serves":2,"cuisine_type":"Middle Eastern","dietary_tags":"Vegetarian,Gluten-Free,breakfast","ingredients_json":json.dumps(["4 large eggs","2x400g tins chopped tomatoes","1 red pepper, diced","1 onion, finely chopped","3 garlic cloves, sliced","1 tsp ground cumin","1 tsp smoked paprika","Olive oil, fresh coriander"]),"steps_json":json.dumps(["Fry onion, pepper, and garlic in olive oil for 5 minutes.","Add spices and tomatoes. Simmer 10 minutes until thick.","Make 4 wells, crack in eggs, cover until whites just set. Top with coriander."])},

{"name":"Overnight Chia Pudding","description":"Creamy chia seed pudding made the night before. Just grab and go.","cook_time_mins":5,"difficulty":"Easy","serves":1,"cuisine_type":"Modern","dietary_tags":"Vegan,Gluten-Free,Dairy-Free,Low-Sugar,breakfast","ingredients_json":json.dumps(["3 tbsp chia seeds","200ml oat milk","1 tsp vanilla extract","1 tbsp maple syrup","Seasonal fruit to top"]),"steps_json":json.dumps(["Mix chia seeds, oat milk, vanilla, and maple syrup in a jar.","Refrigerate overnight for at least 6 hours.","Stir in the morning and top with fresh fruit."])},

{"name":"Keto Bacon & Eggs","description":"Crispy bacon with fried eggs and creamy avocado — a perfect low-carb breakfast.","cook_time_mins":10,"difficulty":"Easy","serves":1,"cuisine_type":"British","dietary_tags":"Keto,Low-Carb,Gluten-Free,High-Protein,breakfast","ingredients_json":json.dumps(["3 rashers smoked back bacon","2 large eggs","Half a ripe avocado","Knob of butter","Salt and black pepper"]),"steps_json":json.dumps(["Fry bacon in a hot pan until the edges are crisp.","Melt butter in the same pan, cook eggs sunny-side up.","Serve alongside sliced avocado with cracked black pepper."])},

{"name":"Vegan Smoothie Bowl","description":"A thick blended bowl topped with granola, chia seeds, and fresh berries.","cook_time_mins":5,"difficulty":"Easy","serves":1,"cuisine_type":"Modern","dietary_tags":"Vegan,Gluten-Free,Dairy-Free,breakfast","ingredients_json":json.dumps(["1 frozen banana","Half cup frozen mango chunks","100ml oat milk","2 tbsp granola","1 tbsp chia seeds","Handful fresh strawberries"]),"steps_json":json.dumps(["Blend banana, mango, and oat milk until thick — it should hold a spoon upright.","Pour into a chilled bowl.","Top with granola, chia seeds, and strawberries."])},

# ── LUNCHES ────────────────────────────────────────────────────────────
{"name":"Vegan Chickpea Curry","description":"A creamy, warming chickpea curry the whole family will love.","cook_time_mins":30,"difficulty":"Easy","serves":4,"cuisine_type":"Indian","dietary_tags":"Vegan,Gluten-Free,Dairy-Free,High-Protein,High-Fibre,Halal,lunch,Budget-Friendly","ingredients_json":json.dumps(["2x400g tins chickpeas, drained","400g tin chopped tomatoes","400ml tin coconut milk","1 large onion, diced","4 garlic cloves, minced","2 tsp curry powder","1 tsp ground cumin","1 tsp turmeric","Fresh coriander and basmati rice to serve"]),"steps_json":json.dumps(["Fry onion and garlic until golden, about 7 minutes.","Add spices, fry 2 minutes until fragrant. Add tomatoes, coconut milk, chickpeas.","Simmer 20 minutes. Serve over rice with fresh coriander."])},

{"name":"Spiced Lentil Soup","description":"A hearty, warming red lentil soup with cumin and a squeeze of lemon.","cook_time_mins":30,"difficulty":"Easy","serves":4,"cuisine_type":"Middle Eastern","dietary_tags":"Vegan,Gluten-Free,Dairy-Free,High-Protein,High-Fibre,Halal,lunch,DASH Diet","ingredients_json":json.dumps(["200g red lentils, rinsed","400g tin chopped tomatoes","1 litre good vegetable stock","1 onion, diced","2 garlic cloves","1 tsp ground cumin","Half tsp turmeric","Juice of 1 lemon, fresh parsley"]),"steps_json":json.dumps(["Fry onion and garlic until soft. Add spices, cook 1 minute.","Add lentils, tomatoes, and stock. Bring to a boil then simmer 25 minutes.","Squeeze in lemon juice, taste and season. Top with parsley."])},

{"name":"Falafel Wrap","description":"Crispy falafel in a warm flatbread with hummus and fresh salad.","cook_time_mins":20,"difficulty":"Easy","serves":2,"cuisine_type":"Middle Eastern","dietary_tags":"Vegan,High-Protein,Halal,lunch","ingredients_json":json.dumps(["8 falafels (shop-bought or homemade)","2 large flatbreads","4 tbsp hummus","Handful baby gem lettuce","2 ripe tomatoes, sliced","Half cucumber, sliced","Tahini sauce and lemon to serve"]),"steps_json":json.dumps(["Heat falafels at 200C for 8 minutes until crisp.","Warm flatbreads in a dry pan for 30 seconds each side.","Spread hummus generously, add salad and falafel, drizzle with tahini and lemon."])},

{"name":"Paneer Tikka Wrap","description":"Chargrilled spiced paneer bites with cooling cucumber raita in a flatbread.","cook_time_mins":25,"difficulty":"Medium","serves":2,"cuisine_type":"Indian","dietary_tags":"Vegetarian,High-Protein,Indian Vegetarian,lunch","ingredients_json":json.dumps(["250g paneer, cut into cubes","2 large flatbreads","150g natural yogurt","1 tsp cumin, 1 tsp turmeric, 1 tsp garam masala","Half cucumber, grated","Fresh mint, lemon juice"]),"steps_json":json.dumps(["Mix half the yogurt with spices. Coat paneer cubes. Marinate 15 minutes.","Grill on highest heat, 3-4 minutes each side until charred.","Stir cucumber and mint into remaining yogurt for raita. Serve paneer in wraps."])},

{"name":"West African Groundnut Soup","description":"A rich, peanut-based tomato soup with sweet potato — a classic West African dish.","cook_time_mins":40,"difficulty":"Medium","serves":4,"cuisine_type":"West African","dietary_tags":"Vegan,Gluten-Free,Dairy-Free,Halal,lunch","ingredients_json":json.dumps(["3 tbsp smooth peanut butter","2 medium sweet potatoes, cubed","400g tin chopped tomatoes","1 litre vegetable stock","1 onion, 3 garlic cloves","1 tsp chilli flakes","Fresh coriander"]),"steps_json":json.dumps(["Fry onion and garlic until golden. Add sweet potato, tomatoes, stock, and chilli.","Simmer 25 minutes until potato is very tender.","Stir in peanut butter until fully dissolved. Taste and season. Top with coriander."])},

{"name":"Tuna Nicoise Salad","description":"A classic French salad with tuna, green beans, soft-boiled eggs, and olives.","cook_time_mins":20,"difficulty":"Easy","serves":2,"cuisine_type":"French","dietary_tags":"Gluten-Free,Dairy-Free,High-Protein,Pescatarian,lunch,Mediterranean","ingredients_json":json.dumps(["2x145g tins good tuna in olive oil","2 large eggs","150g fine green beans","4 small new potatoes","Kalamata olives","1 tsp Dijon mustard, 2 tbsp olive oil, 1 tbsp red wine vinegar"]),"steps_json":json.dumps(["Boil potatoes 12 minutes, add eggs for last 7. Blanch beans 3 minutes.","Whisk Dijon, olive oil, and vinegar for dressing. Season well.","Arrange everything in bowls and drizzle with dressing."])},

# ── DINNERS ────────────────────────────────────────────────────────────
{"name":"Baked Salmon & Roasted Veg","description":"Simple oven-baked salmon with caramelised seasonal vegetables and fresh dill.","cook_time_mins":30,"difficulty":"Easy","serves":2,"cuisine_type":"Modern","dietary_tags":"Pescatarian,Gluten-Free,Dairy-Free,High-Protein,Keto,Low-Carb,Mediterranean,Pregnancy-Safe,dinner","ingredients_json":json.dumps(["2x180g salmon fillets","1 courgette, sliced","1 large red pepper, chunks","1 red onion, wedges","3 tbsp olive oil","1 lemon, fresh dill","Sea salt and cracked pepper"]),"steps_json":json.dumps(["Preheat oven to 200C. Toss chopped veg in 2 tbsp olive oil on a large tray. Roast 10 minutes.","Nestle salmon among the veg, drizzle with remaining oil, season, add lemon slices.","Roast 12-15 minutes until salmon flakes easily. Scatter with fresh dill."])},

{"name":"Chicken Tikka Masala","description":"Tender chicken in a luscious, mildly spiced tomato cream sauce.","cook_time_mins":40,"difficulty":"Medium","serves":4,"cuisine_type":"Indian","dietary_tags":"Gluten-Free,High-Protein,Halal,dinner","ingredients_json":json.dumps(["600g chicken breast, cubed","400g tin chopped tomatoes","150ml double cream","1 large onion","4 garlic cloves","1 tbsp fresh ginger paste","2 tbsp tikka masala paste","Fresh coriander and basmati rice to serve"]),"steps_json":json.dumps(["Coat chicken in tikka paste. Grill or fry until charred in places, about 8 minutes.","Fry onion, garlic, and ginger until deeply golden. Add tomatoes, simmer 10 minutes.","Pour in cream, stir in chicken. Simmer 10 minutes until rich and coating. Serve with rice."])},

{"name":"One-Pot Mushroom Risotto","description":"Creamy, comforting risotto made in a single pot with minimal washing up.","cook_time_mins":35,"difficulty":"Medium","serves":2,"cuisine_type":"Italian","dietary_tags":"Vegetarian,Gluten-Free,One-Pot Meals,dinner","ingredients_json":json.dumps(["300g mixed mushrooms (chestnut, shiitake, portobello)","200g arborio rice","1 litre warm vegetable stock","1 glass dry white wine","1 shallot, 2 garlic cloves","50g parmesan, grated","30g cold butter","Fresh parsley"]),"steps_json":json.dumps(["Fry shallot until translucent. Add mushrooms, cook until golden and liquid has evaporated.","Add rice, stir for 1 minute. Pour in wine, stir until absorbed.","Add warm stock one ladle at a time, stirring constantly, for 18-20 minutes. Remove from heat. Beat in cold butter and parmesan. Rest 2 minutes."])},

{"name":"Caribbean Jerk Chicken","description":"Fiery jerk-marinated chicken legs with fragrant allspice and scotch bonnet.","cook_time_mins":50,"difficulty":"Medium","serves":4,"cuisine_type":"Caribbean","dietary_tags":"Gluten-Free,Dairy-Free,High-Protein,Halal,dinner","ingredients_json":json.dumps(["4 chicken leg quarters","3 tbsp jerk seasoning paste","Juice of 2 limes","1 tbsp olive oil","1 tsp dried allspice","Fresh thyme sprigs","Rice and peas to serve"]),"steps_json":json.dumps(["Score the chicken deeply. Rub all over with jerk paste, lime juice, and oil. Marinate at least 1 hour (overnight is best).","Preheat oven to 200C. Roast on a rack for 40-45 minutes until skin is deeply caramelised.","Rest 5 minutes. Serve with rice and peas and extra lime."])},

{"name":"Pasta Aglio e Olio","description":"The simplest Italian classic — garlic, olive oil, chilli, and parsley.","cook_time_mins":15,"difficulty":"Easy","serves":2,"cuisine_type":"Italian","dietary_tags":"Vegetarian,Budget-Friendly,Student Meals,5-Ingredient Meals,dinner","ingredients_json":json.dumps(["200g good spaghetti","6 garlic cloves, very thinly sliced","5 tbsp extra virgin olive oil","1 tsp dried chilli flakes","Large handful flat-leaf parsley, chopped","Sea salt"]),"steps_json":json.dumps(["Cook spaghetti in generously salted water until al dente. Reserve 150ml pasta water before draining.","Warm olive oil in a wide pan. Gently fry garlic on lowest heat until just golden — don't let it burn.","Add chilli, then drained pasta and a splash of pasta water. Toss vigorously until creamy. Add parsley, toss again, serve immediately."])},

{"name":"Golden Turmeric Soup","description":"A vibrant, healing soup with turmeric, ginger, lentils, and coconut milk.","cook_time_mins":30,"difficulty":"Easy","serves":4,"cuisine_type":"Modern","dietary_tags":"Vegan,Gluten-Free,Dairy-Free,Anti-Inflammatory,dinner,MIND Diet","ingredients_json":json.dumps(["150g red lentils","400ml tin coconut milk","1 litre vegetable stock","2 tsp ground turmeric","1 tbsp fresh ginger, grated","1 onion, 2 garlic cloves","Juice of 1 lemon","Fresh coriander, lots of cracked black pepper"]),"steps_json":json.dumps(["Fry onion and garlic until soft. Add ginger and turmeric — cook 2 minutes. Add generous black pepper (activates the turmeric).","Add lentils, stock, and coconut milk. Simmer 20 minutes until lentils are completely soft.","Blend until silky smooth. Stir in lemon juice. Serve with coriander."])},

{"name":"Black Bean Tacos","description":"Crispy corn tortillas loaded with spiced black beans, avocado, and zingy salsa.","cook_time_mins":20,"difficulty":"Easy","serves":2,"cuisine_type":"Mexican","dietary_tags":"Vegan,Gluten-Free,Dairy-Free,High-Fibre,Budget-Friendly,dinner,Latin American","ingredients_json":json.dumps(["2x400g tins black beans, drained","8 small corn tortillas","1 large ripe avocado","2 ripe tomatoes","1 lime","1 tsp ground cumin, 1 tsp smoked paprika","Fresh coriander, 1 jalapeño"]),"steps_json":json.dumps(["Fry beans with cumin and paprika in olive oil for 5 minutes until slightly caramelised.","Dice tomatoes, coriander, and jalapeño. Squeeze in half a lime, season with salt — that's your salsa.","Warm tortillas in a dry pan 30 seconds each side. Fill with beans, sliced avocado, and salsa."])},

# ── ADDITIONAL DIETARY COVERAGE ────────────────────────────────────────
{"name":"Low-FODMAP Chicken Soup","description":"A gentle, soothing chicken soup that is safe for IBS sufferers.","cook_time_mins":35,"difficulty":"Easy","serves":4,"cuisine_type":"British","dietary_tags":"Low-FODMAP,Gluten-Free,Dairy-Free,Halal,lunch","ingredients_json":json.dumps(["2 chicken breasts","2 carrots, sliced","2 celery stalks","1 litre low-FODMAP chicken stock","1 tsp dried thyme","Salt and pepper","Rice noodles"]),"steps_json":json.dumps(["Simmer chicken breasts in stock for 20 minutes. Remove and shred with forks.","Add carrots, celery, and thyme to the stock. Cook 10 minutes.","Add noodles and shredded chicken, cook 5 more minutes. Season and serve."])},

{"name":"Diabetic-Friendly Stuffed Peppers","description":"Roasted peppers filled with a low-GI mixture of brown rice, lentils, and herbs.","cook_time_mins":50,"difficulty":"Medium","serves":4,"cuisine_type":"Mediterranean","dietary_tags":"Diabetic-Friendly,Vegetarian,Gluten-Free,Dairy-Free,dinner","ingredients_json":json.dumps(["4 large bell peppers","150g brown rice","400g tin lentils, drained","400g tin chopped tomatoes","1 onion, 2 garlic cloves","1 tsp ground cumin","Fresh parsley, olive oil"]),"steps_json":json.dumps(["Cook rice. Fry onion and garlic with cumin. Add tomatoes and lentils — cook 5 minutes.","Mix with rice and chopped parsley.","Cut tops off peppers, remove seeds, fill with mixture. Bake at 180C for 30 minutes."])},

{"name":"Anti-Inflammatory Salmon Bowl","description":"Omega-3 rich salmon over brown rice with edamame and a sesame dressing.","cook_time_mins":25,"difficulty":"Easy","serves":2,"cuisine_type":"Asian","dietary_tags":"Gluten-Free,Dairy-Free,High-Protein,Anti-Inflammatory,Pescatarian,dinner,Athlete","ingredients_json":json.dumps(["2 salmon fillets","200g brown rice","100g edamame beans","2 tbsp sesame oil","1 tbsp low-sodium soy sauce","1 tsp ginger, grated","Sesame seeds, spring onion"]),"steps_json":json.dumps(["Cook rice. Grill salmon for 4 minutes each side.","Microwave edamame for 2 minutes. Mix sesame oil, soy sauce, and ginger for dressing.","Arrange rice, salmon, and edamame in bowls. Drizzle with dressing, top with seeds."])},

{"name":"Jain Dal Tadka","description":"A flavourful yellow lentil dish made without onion or garlic — fully Jain-friendly.","cook_time_mins":30,"difficulty":"Medium","serves":2,"cuisine_type":"Indian","dietary_tags":"Jain,Vegan,Gluten-Free,Dairy-Free,lunch,Indian Vegetarian","ingredients_json":json.dumps(["150g yellow lentils","400g tin chopped tomatoes","1 tsp cumin seeds","1 tsp turmeric, 1 tsp coriander powder","2 tbsp ghee or neutral oil","Fresh coriander","Salt"]),"steps_json":json.dumps(["Boil lentils in salted water until completely soft, about 20 minutes. Mash slightly.","Heat ghee in a small pan. Sizzle cumin seeds until they pop. Add tomatoes and spices, cook 5 minutes.","Combine with lentils and simmer 5 more minutes. Top with fresh coriander."])},

{"name":"Heart-Healthy Grilled Mackerel","description":"Omega-3 rich mackerel grilled simply with lemon and served over a green salad.","cook_time_mins":15,"difficulty":"Easy","serves":2,"cuisine_type":"Mediterranean","dietary_tags":"Pescatarian,Gluten-Free,Dairy-Free,Heart-Healthy,Anti-Inflammatory,dinner","ingredients_json":json.dumps(["2 fresh mackerel fillets","1 lemon, 2 tbsp olive oil","Mixed salad leaves","Cucumber, radishes","Fresh dill, salt and pepper"]),"steps_json":json.dumps(["Score mackerel skin and season. Grill on high heat, 4 minutes each side.","Toss salad leaves, cucumber, and radishes with lemon juice and olive oil.","Serve mackerel on the salad, scattered with fresh dill."])},

{"name":"Batch-Cook Veggie Chilli","description":"A big pot of smoky, protein-packed veggie chilli — make once, eat all week.","cook_time_mins":45,"difficulty":"Easy","serves":6,"cuisine_type":"American","dietary_tags":"Vegan,Gluten-Free,Dairy-Free,High-Fibre,Meal-Prep,Budget-Friendly,dinner","ingredients_json":json.dumps(["2x400g tins kidney beans","2x400g tins chopped tomatoes","400g tin sweetcorn","1 red pepper, 1 courgette, 1 onion, 2 garlic cloves","2 tsp chilli powder, 1 tsp cumin, 1 tsp smoked paprika","Olive oil, rice to serve"]),"steps_json":json.dumps(["Fry onion, garlic, and pepper in olive oil 5 minutes.","Add all remaining ingredients and stir. Bring to a boil.","Simmer 35 minutes. Serve over rice. Freeze portions for the week."])},
]


def seed_database():
    from database import get_db, init_db
    init_db()
    conn = get_db()
    c = conn.cursor()
    existing = c.execute("SELECT COUNT(*) FROM recipes").fetchone()[0]
    if existing > 0:
        print(f"Database already has {existing} recipes — skipping seed.")
        conn.close()
        return
    for r in RECIPES:
        c.execute("""
            INSERT INTO recipes
            (name, description, cook_time_mins, difficulty, serves,
             cuisine_type, dietary_tags, ingredients_json, steps_json)
            VALUES (?,?,?,?,?,?,?,?,?)
        """, (r["name"], r["description"], r["cook_time_mins"], r["difficulty"],
              r["serves"], r["cuisine_type"], r["dietary_tags"],
              r["ingredients_json"], r["steps_json"]))
    conn.commit()
    conn.close()
    print(f"Seeded {len(RECIPES)} recipes successfully.")


if __name__ == "__main__":
    seed_database()
